language: bash
services: docker

env:
  - R_BASE_VERSION=3.6.2 MRAN_SNAPSHOT_DATE=2020-04-01
  - R_BASE_VERSION=3.6.3 MRAN_SNAPSHOT_DATE=2020-06-01
  - R_BASE_VERSION=3.6.3 MRAN_SNAPSHOT_DATE=2021-01-16

script:
  - ./scripts/cibuild

deploy:
  - provider: script
    script: "scripts/cipublish"
    on:
      repo: planetrics/r-docker
      branch: master
