#!/bin/bash

set -e
set -u

if [[ -n "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
"Usage: $(basename "$0")
Build container images from templates.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        sed -e "s/%%R_BASE_VERSION%%/$R_BASE_VERSION/" \
            -e "s/%%MRAN_SNAPSHOT_DATE%%/$MRAN_SNAPSHOT_DATE/" \
            "Dockerfile.template" > Dockerfile

        docker \
            build -t "quay.io/vividfinancepg/r:$R_BASE_VERSION-$MRAN_SNAPSHOT_DATE" .

        docker images
    fi
fi
